script:
  - bin/rake
language: ruby
cache: bundler
notifications:
  slack: tanganetwork:zpPQzEDWf5HfZ77a2vpEGHXS
addons:
  code_climate:
    repo_token: 6480502c92bec9a4fa22e761dbe2c7908c05763c17bbc327af9aebc03e6f5cf1
